#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

version: '3'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  datascale:
    # Uncomment if you want to add a different Dockerfile in the .devcontainer folder
    build:
      context: ../
      dockerfile: .devcontainer/datascale/Dockerfile

    # Uncomment if you want to expose any additional ports. The snippet below exposes port 3000.
    # ports:
    #   - 3000:3000
    
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace

      # This lets you avoid setting up Git again in the container
      - ~/.gitconfig:/root/.gitconfig

      # Uncomment the next line if you plan to install the Docker CLI. See the docker-in-docker-compose definition for details.
      # - /var/run/docker.sock:/var/run/docker.sock 

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity 
    
  redisgraph:
    image: "redislabs/redisgraph:latest"
    ports:
      - 6379:6379
  minio:
    image: "minio/minio:latest"
    ports:
      - 9000:9000
    command: ["server", "/data"]
